### ISSUE TITLE
team pictures next to each other

### ISSUE THREAD

**Issue by Wallensteiner0** [Wallensteiner0/BookingApp_Frontend#39]

**Comment by Wallensteiner0** [comment]
Hallo Gerhard,
ich habe dich zum Ticket hinzugefügt, da du ja gestern auch daran gearbeitet hast. Könntest du bitte kurz beschreiben, welche Änderungen du vorgenommen hast? Die Bilder waren in meinem Merge bereits nebeneinander, aber ich vermute, dass du zwischenzeitlich noch etwas an Bootstrap angepasst hast. Vielen Dank für deine Unterstützung!

**Comment by Wallensteiner0** [comment]
@ZuzkaGlaess In the case you want to change your picture, please make sure to upload a quare-sized one. Yours looks now a litte closer due to the quareness but small picture.

**Comment by ZuzkaGlaess** [comment]
implemented
