### ISSUE TITLE
As a registered user, I would like to be able to log in with my username or email address and password

### ISSUE THREAD

**Issue by ZuzkaGlaess** [Wallensteiner0/BookingApp_Frontend#5]
Create Login dialog so customer, instructor or admin can log in.

- [ ] Login dialog

**Comment by Wallensteiner0** [comment]
updated frontend site according to bootstrap
![grafik](https://github.com/Wallensteiner0/BookingApp_Frontend/assets/52046300/26121ca9-b5e0-4ce0-8ca1-5f2893944366)

**Comment by ZuzkaGlaess** [comment]
Login jQuery missing, needs fix, moving back into in-progress
