### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by ZuzkaGlaess** [Wallensteiner0/BookingApp_Frontend#6]

**Comment by Wallensteiner0** [comment]
Updated according to bootstrap
- added folder "js" for all javascript files
- added forum-handler.js
- modified forum = ready for review

**Comment by Wallensteiner0** [comment]
Questions are now clickable and will open



![Image](https://github.com/Wallensteiner0/BookingApp_Frontend/assets/52046300/ddbc9d94-560f-4e1a-b70c-4e4d27607bb5)

**Comment by Wallensteiner0** [comment]
updated the outlook
